# config/packages/security.yaml
security:
    access_denied_url: /security/access_denied
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        users:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:
                path:   security_logout
            guard:
                authenticators:
                    - App\Security\AppLdapAuthenticator
#            remember_me:
#                secret:   '%kernel.secret%'
#                lifetime: 86400
#                path:     /
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                #always_remember_me: true

