SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE indicator;
INSERT INTO indicator VALUES (1, NULL, (SELECT id FROM unit WHERE symbol = 'photo'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Mold', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (2, 1, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Cavity Number', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (3, 1, (SELECT id FROM unit WHERE symbol = 'kn'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Clamping Force', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (4, 1, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Versions', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (5, 1, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Lifting Link', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (6, 5, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Diameter M:', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (7, 1, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Centring Ring', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (8, 7, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Diameter Fixed Side', 2, 1, NULL, NULL);
INSERT INTO indicator VALUES (9, 7, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Diameter Moving Side', 2, 1, NULL, NULL);
INSERT INTO indicator VALUES (10, 1, (SELECT id FROM unit WHERE symbol = 'hand-drawing'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Sprue Drawing', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (11, 1, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Nbr Gates', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (12, 1, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Gate Diameter', 1, 1, NULL, 2);
INSERT INTO indicator VALUES (13, 1, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Feed Runner Diameter', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (14, 1, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Mold Nozzle', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (15, 14, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Radius', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (16, 14, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Diameter', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (17, 1, (SELECT id FROM unit WHERE symbol = 'kg'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Weight', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (18, 1, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Thickness', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (19, 1, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Width', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (20, 1, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Height', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (21, 1, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Ejection', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (22, 21, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Mechanical', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (23, 21, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Hydraulic', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (24, 1, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Ejector Nut Threading M:', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (25, 1, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Cores', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (26, 1, (SELECT id FROM unit WHERE symbol = 'photo'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Hot Runner', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (27, 26, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Zones', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (28, 1, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Shut Off Nozzles', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (29, 28, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Hydraulic', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (30, 28, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Pneumatic', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (31, 28, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Electric', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (32, 1, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Pressure Sensor', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (33, 1, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Temperature Sensor', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (34, 1, (SELECT id FROM unit WHERE symbol = 'photo'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Cooling', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (35, 34, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Fixed Side', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (36, 35, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Circuits', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (37, 35, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Bridge', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (38, 35, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Sequential', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (39, 35, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Thermoregulator', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (40, 34, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Moving Side', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (41, 40, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Circuits', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (42, 40, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Bridge', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (43, 40, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Sequential', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (44, 40, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Thermoregulator', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (45, 1, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Operating Mode', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (46, 40, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Auto', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (47, 40, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Semi Auto', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (48, 1, (SELECT id FROM unit WHERE symbol = 'photo'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Cinematic', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (49, 1, (SELECT id FROM unit WHERE symbol = 'photo'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Mold Cavity Side', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (50, 1, (SELECT id FROM unit WHERE symbol = 'photo'), (SELECT id FROM type_of_device WHERE name LIKE 'Mold'), 'Mold Core Side', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (51, NULL, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Imm', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (52, 51, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Screw Diameter', 3, 1, NULL, NULL);
INSERT INTO indicator VALUES (53, 51, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Nozzle', 3, 1, NULL, NULL);
INSERT INTO indicator VALUES (54, 53, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Radius', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (55, 53, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Diameter', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (56, 51, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Ejector Tail', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (57, 56, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Length', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (58, 56, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Diameter', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (59, 56, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Threading M:', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (60, NULL, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'Material'), 'Material', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (61, 60, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'Material'), 'Material Type', 3, 1, NULL, NULL);
INSERT INTO indicator VALUES (62, 61, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'Material'), 'Reference', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (63, 61, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'Material'), 'Colorant', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (64, 61, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'Material'), 'Adjuvant', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (65, 61, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'Material'), 'Batch', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (66, 61, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'Material'), 'Recycled Material', 1, 1, NULL, 2);
INSERT INTO indicator VALUES (67, 61, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'Material'), 'Drying', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (68, 67, (SELECT id FROM unit WHERE symbol = 'hour'), (SELECT id FROM type_of_device WHERE name LIKE 'Material'), 'Time', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (69, 61, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'Material'), 'Fluidity Index', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (70, NULL, (SELECT id FROM unit WHERE symbol = 'bool'), (SELECT id FROM type_of_device WHERE name LIKE 'Robot'), 'Robot', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (71, 70, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'Robot'), 'Type', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (72, 70, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'Robot'), 'Programme Number', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (73, 70, (SELECT id FROM unit WHERE symbol = 'photo'), (SELECT id FROM type_of_device WHERE name LIKE 'Robot'), 'Gripper', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (74, 73, (SELECT id FROM unit WHERE symbol = 'photo'), (SELECT id FROM type_of_device WHERE name LIKE 'Robot'), 'Air And Electrical Connection', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (75, 73, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Robot'), 'Vacuum', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (76, 73, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'Robot'), 'Air Circuits', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (77, 70, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'Robot'), 'Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (78, 70, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'Robot'), 'Camera', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (79, NULL, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Settings', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (80, 79, (SELECT id FROM unit WHERE symbol = 'photo'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Cycle Grafcet', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (81, 79, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mold Closing', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (82, 81, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure', 6, 1, NULL, NULL);
INSERT INTO indicator VALUES (83, 81, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Speed', 6, 1, NULL, NULL);
INSERT INTO indicator VALUES (84, 81, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Steps', 6, 1, NULL, NULL);
INSERT INTO indicator VALUES (85, 81, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Protection Stroke', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (86, 85, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (87, 85, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (88, 85, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (89, 81, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'End Of Mold Protection Toggle', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (90, 81, (SELECT id FROM unit WHERE symbol = 'kn'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Clamping Force', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (91, 81, (SELECT id FROM unit WHERE symbol = 'kn'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Actual Clamping Force', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (92, 79, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mold Opening', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (93, 92, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Opening Stroke', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (94, 92, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure', 6, 1, NULL, NULL);
INSERT INTO indicator VALUES (95, 92, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Speed', 6, 1, NULL, NULL);
INSERT INTO indicator VALUES (96, 92, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Steps', 6, 1, NULL, NULL);
INSERT INTO indicator VALUES (97, 92, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Decompression Stroke', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (98, 97, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (99, 97, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (100, 97, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Stroke', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (101, 92, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Nut Closing', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (102, 101, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (103, 101, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (104, 92, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Nut Opening', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (105, 104, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (106, 104, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (107, 92, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mold Spring Using', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (108, 92, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Real Cycle Time', 1, 1, NULL, 2);
INSERT INTO indicator VALUES (109, 92, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mini Opening Stroke For Robot', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (110, 79, (SELECT id FROM unit WHERE symbol = 'bool'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Ejection', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (111, 110, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Ejector In', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (112, 111, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure', 3, 1, NULL, NULL);
INSERT INTO indicator VALUES (113, 111, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Speed', 3, 1, NULL, NULL);
INSERT INTO indicator VALUES (114, 111, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Stroke', 3, 1, NULL, NULL);
INSERT INTO indicator VALUES (115, 111, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Rear Position', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (116, 111, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Ejector Position Start', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (117, 110, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Ejector Out', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (118, 117, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure', 3, 1, NULL, NULL);
INSERT INTO indicator VALUES (119, 117, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Speed', 3, 1, NULL, NULL);
INSERT INTO indicator VALUES (120, 117, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Stroke', 3, 1, NULL, NULL);
INSERT INTO indicator VALUES (121, 117, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Ejector Time Forward', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (122, 117, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Ejector Counter', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (123, 110, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Ejection Delay', 1, 1, NULL, 2);
INSERT INTO indicator VALUES (124, 79, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Cores', 10, 1, NULL, NULL);
INSERT INTO indicator VALUES (125, 124, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Core In', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (126, 125, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (127, 125, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (128, 125, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Priority', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (129, 125, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Position', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (130, 125, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Start Mold Position', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (131, 125, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mold Control Point', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (132, 125, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'In Priority', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (133, 125, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Without Pressure After Entry', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (134, 125, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Without Robot Authorisation', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (135, 125, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Time Variable', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (136, 135, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Entry Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (137, 135, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Monitoring Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (138, 125, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Superimposed On Mold Movement', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (139, 125, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Demoulding With Core', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (140, 125, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Unscrewing Core', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (141, 124, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Core Out', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (142, 141, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (143, 141, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (144, 141, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Priority', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (145, 141, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Position', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (146, 141, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Start Mold Position', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (147, 141, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mold Control Point', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (148, 141, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Out Priority', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (149, 141, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Without Pressure After Entry', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (150, 141, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Without Robot Authorisation', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (151, 141, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Time Variable', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (152, 151, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Exit Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (153, 151, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Monitoring Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (154, 141, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Superimposed On Mold Movement', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (155, 141, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'During Cooling Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (156, 153, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (157, 141, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'After Ejection Forward', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (158, 141, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Unscrewing Core', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (159, 79, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Cooling', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (160, 159, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Fixed Side Zones', 30, 1, NULL, NULL);
INSERT INTO indicator VALUES (161, 160, (SELECT id FROM unit WHERE symbol = 'l/mn'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Flow', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (162, 160, (SELECT id FROM unit WHERE symbol = 'photo'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Water Box', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (163, 159, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Moving Side Zones', 30, 1, NULL, NULL);
INSERT INTO indicator VALUES (164, 163, (SELECT id FROM unit WHERE symbol = 'l/mn'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Flow', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (165, 163, (SELECT id FROM unit WHERE symbol = 'photo'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Water Box', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (166, 79, (SELECT id FROM unit WHERE symbol = 'bool'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Rotating Plate', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (167, 166, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Actuation During Mold Closing', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (168, 166, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mold Position Actuation Stop', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (169, 166, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Service Mode', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (170, 166, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Direction', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (171, 170, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Rotating Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (172, 171, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Left', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (173, 171, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Right', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (174, 170, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (175, 174, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Left', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (176, 174, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Right', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (177, 166, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Station', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (178, 177, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Final Position Of Stroke Sensor', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (179, 178, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Left', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (180, 178, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Right', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (181, 177, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Breaking Stroke', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (182, 181, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Left', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (183, 181, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Right', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (184, 79, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Cylinders Temperature', 3, 1, NULL, NULL);
INSERT INTO indicator VALUES (185, 184, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Zones', 9, 1, NULL, NULL);
INSERT INTO indicator VALUES (186, 185, (SELECT id FROM unit WHERE symbol = '°c '), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mini Tolerance', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (187, 185, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Maxi Tolerance', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (188, 184, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Injection Unit Alimentation', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (189, 184, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mass Temperature', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (190, 184, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Standby Temperature', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (191, 79, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Oil Machine Temperature', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (192, 191, (SELECT id FROM unit WHERE symbol = '°c '), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Set Value', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (193, 191, (SELECT id FROM unit WHERE symbol = '°c '), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Actual', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (194, 79, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Hot Runner Temperature', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (195, 194, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Imm', 80, 1, NULL, NULL);
INSERT INTO indicator VALUES (196, 195, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Zones', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (197, 195, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Average Consumption Of Nozzles', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (198, 194, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'External Regulator', 80, 1, NULL, NULL);
INSERT INTO indicator VALUES (199, 198, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Zones', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (200, 198, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Average Consumption Of Nozzles', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (201, 79, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Injection Unit', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (202, 201, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Advance Stroke Unit', 2, 1, NULL, NULL);
INSERT INTO indicator VALUES (203, 202, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (204, 202, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (205, 201, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Backward Stroke Unit', 2, 1, NULL, NULL);
INSERT INTO indicator VALUES (206, 205, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (207, 205, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (208, 201, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Application Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (209, 201, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure Rise Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (210, 79, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Injection Parameters', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (211, 210, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Switchover', 3, 1, NULL, NULL);
INSERT INTO indicator VALUES (212, 211, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Switch Over Mode', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (213, 212, (SELECT id FROM unit WHERE symbol = 'cm3'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Stroke', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (214, 212, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (215, 212, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Time', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (216, 212, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Internal Mold Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (217, 212, (SELECT id FROM unit WHERE symbol = 'cm3'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mask', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (218, 211, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Switch Over Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (219, 211, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Specific Injection Pressure Increased', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (220, 211, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Delay Injection Time', 1, 1, NULL, 2);
INSERT INTO indicator VALUES (221, 211, (SELECT id FROM unit WHERE symbol = 'mm/s'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Injection Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (222, 211, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Injection Profile', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (223, 222, (SELECT id FROM unit WHERE symbol = 'mm/s'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Step', 10, 1, NULL, NULL);
INSERT INTO indicator VALUES (224, 222, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Injection Time', 1, 1, NULL, 2);
INSERT INTO indicator VALUES (225, 222, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Limit Injection Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (226, 211, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Holding Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (227, 226, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Step', 10, 1, NULL, NULL);
INSERT INTO indicator VALUES (228, 226, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Holding Time', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (229, 211, (SELECT id FROM unit WHERE symbol = 'cm3'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Cushion', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (230, 211, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Cooling Time', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (231, 79, (SELECT id FROM unit WHERE symbol = 'bool'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Intrusion Injection', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (232, 231, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Time', 1, 1, NULL, 2);
INSERT INTO indicator VALUES (233, 231, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (234, 79, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Injection Time', 3, 1, NULL, 2);
INSERT INTO indicator VALUES (235, 79, (SELECT id FROM unit WHERE symbol = 'photo'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Filling Progression', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (236, 79, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Valve Gate Screw Etancheity Test', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (237, 79, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Dosing', 3, 1, NULL, NULL);
INSERT INTO indicator VALUES (238, 237, (SELECT id FROM unit WHERE symbol = 'cm3'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Dosing Volume', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (239, 237, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Back Pressure', 8, 1, NULL, NULL);
INSERT INTO indicator VALUES (240, 237, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Delay Dosing Time', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (241, 237, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Dosing Time', 1, 1, NULL, 2);
INSERT INTO indicator VALUES (242, 237, (SELECT id FROM unit WHERE symbol = 'cm3'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Decompression', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (243, 237, (SELECT id FROM unit WHERE symbol = 'mm/s'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Decompression Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (244, 237, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Decompression Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (245, 237, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Dosing Speed', 6, 1, NULL, NULL);
INSERT INTO indicator VALUES (246, 237, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Decompression Before Dosing', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (247, 246, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Stroke', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (248, 246, (SELECT id FROM unit WHERE symbol = 'mm/s'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (249, 79, (SELECT id FROM unit WHERE symbol = 'hydraulic OR pneumatic'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Shut Off Nozzles Type', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (250, 79, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Shut Off Nozzles', 24, 1, NULL, NULL);
INSERT INTO indicator VALUES (251, 250, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Injection', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (252, 251, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Opening', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (253, 252, (SELECT id FROM unit WHERE symbol = 'cm3'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Volume', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (254, 252, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Stroke', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (255, 252, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (256, 252, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Temperature', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (257, 251, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Closing', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (258, 257, (SELECT id FROM unit WHERE symbol = 'cm3'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Volume', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (259, 257, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Stroke', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (260, 257, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (261, 257, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Temperature', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (262, 250, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Holding', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (263, 262, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (264, 262, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Delay', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (265, 79, (SELECT id FROM unit WHERE symbol = 'bool'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Monitoring Of Parameters', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (266, 265, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Cycle Time', 1, 1, NULL, 2);
INSERT INTO indicator VALUES (267, 266, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Maxi Tolerance', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (268, 266, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mini Tolerance', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (269, 265, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Dosing Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (270, 269, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Maxi Tolerance', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (271, 269, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mini Tolerance', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (272, 265, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Injection Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (273, 272, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Maxi Tolerance', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (274, 272, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mini Tolerance', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (275, 265, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Cushion', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (276, 275, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Maxi Tolerance', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (277, 275, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mini Tolerance', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (278, 265, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Switchover Point Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (279, 278, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Maxi Tolerance', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (280, 278, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mini Tolerance', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (281, 265, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Injection Pressure Maximum', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (282, 281, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Maxi Tolerance', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (283, 281, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mini Tolerance', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (284, 79, (SELECT id FROM unit WHERE symbol = 'bool'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Babyplast', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (285, 284, (SELECT id FROM unit WHERE symbol = '°c'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Temperature', 4, 1, NULL, NULL);
INSERT INTO indicator VALUES (286, 284, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Dosing', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (287, 284, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Cooling Time', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (288, 284, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), '1st Injection Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (289, 284, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Timeout Pressure Change', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (290, 284, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), '2nd Injection Pressure', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (291, 284, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), '2nd Injection Pressure Time', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (292, 284, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), '2nd Pressure Position', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (293, 284, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Decompression', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (294, 284, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Injection Speed', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (295, 284, (SELECT id FROM unit WHERE symbol = '%'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), '2nd Injection Speed', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (296, 284, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), '2nd Injection Speed Position', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (297, 284, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'End Of Cycle Break Time', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (298, 284, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mold Shut Off Nozzle Delay', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (299, 284, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mold Shut Off Nozzle Time', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (300, 79, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pneumatic Valve', 4, 1, NULL, NULL);
INSERT INTO indicator VALUES (301, 300, (SELECT id FROM unit WHERE symbol = 'nb'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Function', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (302, 301, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mold Closing After Position', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (303, 301, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Injection Start', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (304, 301, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Cooling Time Start', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (305, 301, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Mold Opening After Position', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (306, 300, (SELECT id FROM unit WHERE symbol = 'mm'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Air Supply Flow Position', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (307, 300, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Blowing Time Delay', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (308, 300, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Blowing Time', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (309, 79, (SELECT id FROM unit WHERE symbol = 'bool'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Gaz Injection', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (310, 309, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Circuit', 4, 1, NULL, NULL);
INSERT INTO indicator VALUES (311, 310, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Gaz Delay', 1, 1, NULL, 1);
INSERT INTO indicator VALUES (312, 310, (SELECT id FROM unit WHERE symbol = 'bars'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Pressure', 4, 1, NULL, NULL);
INSERT INTO indicator VALUES (313, 310, (SELECT id FROM unit WHERE symbol = 's'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Holding Time', 4, 1, NULL, 1);
INSERT INTO indicator VALUES (314, 310, (SELECT id FROM unit WHERE symbol = 'bars/s'), (SELECT id FROM type_of_device WHERE name LIKE 'IMM'), 'Ramp', 4, 1, NULL, NULL);
INSERT INTO indicator VALUES (315, NULL, (SELECT id FROM unit WHERE symbol = 'photo'), (SELECT id FROM type_of_device WHERE name LIKE 'part'), 'Parts', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (316, 315, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'part'), 'Weight', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (317, 316, NULL, (SELECT id FROM type_of_device WHERE name LIKE 'part'), 'Part', 16, 1, NULL, NULL);
INSERT INTO indicator VALUES (318, 317, (SELECT id FROM unit WHERE symbol = 'txt'), (SELECT id FROM type_of_device WHERE name LIKE 'part'), 'Description', 1, 1, NULL, NULL);
INSERT INTO indicator VALUES (319, 317, (SELECT id FROM unit WHERE symbol = 'g'), (SELECT id FROM type_of_device WHERE name LIKE 'part'), 'Weight', 1, 1, NULL, 2);
INSERT INTO indicator VALUES (320, 317, (SELECT id FROM unit WHERE symbol = 'g'), (SELECT id FROM type_of_device WHERE name LIKE 'part'), 'Weight Without Holding', 1, 1, NULL, 2);
INSERT INTO indicator VALUES (321, 316, (SELECT id FROM unit WHERE symbol = 'g'), (SELECT id FROM type_of_device WHERE name LIKE 'part'), 'Sprues', 1, 1, NULL, 2);
INSERT INTO indicator VALUES (322, 316, (SELECT id FROM unit WHERE symbol = 'g'), (SELECT id FROM type_of_device WHERE name LIKE 'part'), 'Total', 1, 1, NULL, 2);
INSERT INTO indicator VALUES (323, 316, (SELECT id FROM unit WHERE symbol = 'g'), (SELECT id FROM type_of_device WHERE name LIKE 'part'), 'Total Without Holding', 1, 1, NULL, 2);
SET FOREIGN_KEY_CHECKS = 1;
